# Generated by Django 2.2.5 on 2019-10-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibbo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
