# Generated by Django 2.2.5 on 2019-11-27 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibbo', '0007_auto_20191120_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 9, 51, 40, 619481)),
        ),
    ]
