# Generated by Django 2.2.5 on 2019-11-27 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibbo', '0008_auto_20191127_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 9, 53, 6, 264172)),
        ),
    ]
