# Generated by Django 2.2.5 on 2019-11-27 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibbo', '0011_auto_20191127_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 18, 6, 29, 253293)),
        ),
    ]
